function(require_token text token description)
  string(FIND "${text}" "${token}" index)
  if(index EQUAL -1)
    message(FATAL_ERROR "Windows process containment contract lost: ${description}")
  endif()
endfunction()

function(require_count text pattern minimum description)
  string(REGEX MATCHALL "${pattern}" matches "${text}")
  list(LENGTH matches count)
  if(count LESS minimum)
    message(FATAL_ERROR "Windows process containment contract lost: ${description} (found ${count}, need ${minimum})")
  endif()
endfunction()

file(READ "${SOURCE_ROOT}/src/common/platform/platform_services_windows_impl_internal.h" helpers)
file(READ "${SOURCE_ROOT}/src/common/platform/platform_process_windows.cpp" processes)
file(READ "${SOURCE_ROOT}/src/common/platform/platform_pty_windows.cpp" terminals)

require_token("${helpers}" "JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE" "jobs must kill owned trees when UAM dies")
require_token("${helpers}" "AssignProcessToJobObject(job, process_handle)" "children must be assigned to the kill-on-close job")
require_count("${processes}" "CREATE_SUSPENDED" 2 "captured and stdio children must not run before job assignment")
require_count("${processes}" "CreateKillOnCloseJobForProcess" 2 "captured and stdio children must enter kill-on-close jobs")
require_count("${processes}" "ResumeThread" 2 "captured and stdio children must resume only after containment setup")
require_count("${terminals}" "CREATE_SUSPENDED" 1 "terminal children must not run before job assignment")
require_count("${terminals}" "CreateKillOnCloseJobForProcess" 1 "terminal children must enter a kill-on-close job")
require_count("${terminals}" "ResumeThread" 1 "terminal children must resume after containment setup")
require_token("${terminals}" "pseudo_console_closer" "ConPTY closure must remain owned by the terminal state")
string(FIND "${terminals}" ".detach()" detached_thread)
if(NOT detached_thread EQUAL -1)
  message(FATAL_ERROR "Windows process containment contract lost: terminal cleanup must not detach threads")
endif()
