# Exercise packaging validation with disposable artifacts, including replacements after validation.
set(UAM_REMOTE_RUNNER_ARTIFACT_DIR "${CMAKE_CURRENT_BINARY_DIR}/runner-validation-fixture")
set(UAM_PRODUCT_VERSION "test-version")
set(helper_paths linux-arm64/uam-runner linux-x86_64/uam-runner windows-x86_64/uam-runner.exe)
foreach(helper IN LISTS helper_paths)
  get_filename_component(directory "${UAM_REMOTE_RUNNER_ARTIFACT_DIR}/${helper}" DIRECTORY)
  file(MAKE_DIRECTORY "${directory}")
  file(WRITE "${UAM_REMOTE_RUNNER_ARTIFACT_DIR}/${helper}" "fixture")
  file(SHA256 "${UAM_REMOTE_RUNNER_ARTIFACT_DIR}/${helper}" checksum)
  file(WRITE "${directory}/uam-runner.sha256" "${checksum}")
  file(WRITE "${directory}/uam-runner.version" "${UAM_PRODUCT_VERSION}")
endforeach()
include("${SOURCE_ROOT}/cmake/validate_remote_runners.cmake")
foreach(failure IN ITEMS checksum version missing)
  set(directory "${UAM_REMOTE_RUNNER_ARTIFACT_DIR}/windows-x86_64")
  file(WRITE "${directory}/uam-runner.exe" "fixture")
  file(WRITE "${directory}/uam-runner.version" "${UAM_PRODUCT_VERSION}")
  if(failure STREQUAL "checksum")
    file(APPEND "${directory}/uam-runner.exe" "changed after configure")
  elseif(failure STREQUAL "version")
    file(WRITE "${directory}/uam-runner.version" "old-version")
  else()
    file(REMOVE "${directory}/uam-runner.exe")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DUAM_REMOTE_RUNNER_ARTIFACT_DIR=${UAM_REMOTE_RUNNER_ARTIFACT_DIR}"
    "-DUAM_PRODUCT_VERSION=${UAM_PRODUCT_VERSION}"
    -P "${SOURCE_ROOT}/cmake/validate_remote_runners.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0)
    message(FATAL_ERROR "Packaging accepted ${failure} helper artifacts")
  endif()
  if(failure STREQUAL "missing")
    set(expected "Missing:")
  else()
    set(expected "${failure} mismatch")
  endif()
  if(NOT error MATCHES "${expected}")
    message(FATAL_ERROR "Unexpected ${failure} rejection: ${error}")
  endif()
endforeach()
file(REMOVE_RECURSE "${UAM_REMOTE_RUNNER_ARTIFACT_DIR}")
