function(require_token text token description)
  string(FIND "${text}" "${token}" index)
  if(index EQUAL -1)
    message(FATAL_ERROR "macOS process-spawn contract lost: ${description}")
  endif()
endfunction()

file(READ "${SOURCE_ROOT}/src/common/platform/platform_process_macos.cpp" processes)
file(READ "${SOURCE_ROOT}/src/common/platform/platform_pty_macos.cpp" terminals)
file(READ "${SOURCE_ROOT}/src/common/platform/platform_services_macos_impl_internal.h" helpers)
file(READ "${SOURCE_ROOT}/src/main.cpp" main)

foreach(source IN ITEMS processes terminals)
  require_token("${${source}}" "BuildChildEnvironment" "child environments must be prepared before spawn")
  require_token("${${source}}" "SpawnSuspendedProcess" "providers must use the shared suspended spawn path")
  string(FIND "${${source}}" "fork(" unsafe_fork)
  string(FIND "${${source}}" "setenv(" unsafe_setenv)
  if(NOT unsafe_fork EQUAL -1 OR NOT unsafe_setenv EQUAL -1)
    message(FATAL_ERROR "macOS process-spawn contract lost: provider launchers must remain safe inside multithreaded CEF")
  endif()
endforeach()

require_token("${helpers}" "posix_spawn(" "the shared launcher must use posix_spawn")
require_token("${helpers}" "POSIX_SPAWN_START_SUSPENDED" "children must stay suspended until containment is armed")
require_token("${helpers}" "POSIX_SPAWN_CLOEXEC_DEFAULT" "unlisted manager descriptors must not leak")
require_token("${helpers}" "kMacParentDeathWatchdogArgument" "the watchdog must run through a fresh executable image")
require_token("${helpers}" "SIGCONT" "contained children must resume only after the watchdog is ready")
require_token("${main}" "RunMacParentDeathWatchdogIfRequested" "watchdog mode must dispatch before CEF starts")
