# Local presentation versions never alter the release/runner protocol version.
function(uam_local_build_presentation release local_version output)
  set(presentation "${release}")
  if(NOT local_version STREQUAL "")
    if(NOT local_version MATCHES "^([0-9]+\\.[0-9]+\\.[0-9]+)-alpha-([1-9][0-9]*)$" OR
       NOT CMAKE_MATCH_1 STREQUAL release)
      message(FATAL_ERROR "UAM_LOCAL_BUILD_VERSION must be ${release}-alpha-Q with a positive counter.")
    endif()
    set(presentation "${local_version}")
  endif()
  set(${output} "${presentation}" PARENT_SCOPE)
endfunction()

# All linked checkouts use the common repository's ignored Builds state.
function(uam_reserve_local_build_version source release minimum output)
  if(NOT release MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "A release version X.Y.Z is required.")
  endif()
  if(NOT minimum MATCHES "^(0|[1-9][0-9]*)$" OR minimum GREATER 2147483646)
    message(FATAL_ERROR "The local version minimum must be an integer from 0 to 2147483646.")
  endif()
  if(DEFINED UAM_LOCAL_VERSION_STATE_DIR AND NOT UAM_LOCAL_VERSION_STATE_DIR STREQUAL "")
    set(state_dir "${UAM_LOCAL_VERSION_STATE_DIR}")
  else()
    execute_process(COMMAND git rev-parse --git-common-dir WORKING_DIRECTORY "${source}"
      RESULT_VARIABLE git_result OUTPUT_VARIABLE common_dir OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(git_result EQUAL 0 AND NOT common_dir STREQUAL "")
      get_filename_component(common_dir "${common_dir}" ABSOLUTE BASE_DIR "${source}")
      get_filename_component(shared_root "${common_dir}" DIRECTORY)
    else()
      # An exported source folder has no linked checkouts to share with.
      set(shared_root "${source}")
    endif()
    set(state_dir "${shared_root}/Builds/local-versions")
  endif()
  set(counter_file "${state_dir}/${release}.counter")
  file(LOCK "${counter_file}.lock" GUARD FUNCTION TIMEOUT 30 RESULT_VARIABLE lock_result)
  if(NOT lock_result STREQUAL "0")
    message(FATAL_ERROR "Could not lock the local version counter: ${lock_result}")
  endif()
  set(counter "0")
  if(EXISTS "${counter_file}")
    file(SIZE "${counter_file}" counter_bytes)
    if(counter_bytes GREATER 32)
      message(FATAL_ERROR "Invalid local version counter: ${counter_file}; preserve it and repair the state.")
    endif()
    file(READ "${counter_file}" counter)
    string(STRIP "${counter}" counter)
    if(NOT counter MATCHES "^(0|[1-9][0-9]*)$" OR counter GREATER 2147483646)
      message(FATAL_ERROR "Invalid local version counter: ${counter_file}; preserve it and repair the state.")
    endif()
  endif()
  if(counter LESS minimum)
    set(counter "${minimum}")
  endif()
  math(EXPR next "${counter} + 1")
  file(WRITE "${counter_file}.tmp" "${next}\n")
  file(RENAME "${counter_file}.tmp" "${counter_file}")
  set(${output} "${release}-alpha-${next}" PARENT_SCOPE)
endfunction()

# Reusable allocator entry point: cmake -DUAM_SOURCE_DIR=... -P this-file.
if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  if(NOT DEFINED UAM_SOURCE_DIR)
    get_filename_component(UAM_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  endif()
  file(READ "${UAM_SOURCE_DIR}/CMakeLists.txt" source_cmake)
  string(REGEX MATCH "set\\(UAM_PRODUCT_VERSION [\"]([0-9]+\\.[0-9]+\\.[0-9]+)[\"]\\)" release_match "${source_cmake}")
  if(NOT release_match)
    message(FATAL_ERROR "Could not read the source release version from CMakeLists.txt.")
  endif()
  set(release "${CMAKE_MATCH_1}")
  if(NOT DEFINED UAM_LOCAL_VERSION_MINIMUM)
    set(UAM_LOCAL_VERSION_MINIMUM 0)
    if(release STREQUAL "4.9.0")
      # Historical local artifacts already used alpha-17.
      set(UAM_LOCAL_VERSION_MINIMUM 17)
    endif()
  endif()
  uam_reserve_local_build_version("${UAM_SOURCE_DIR}" "${release}" "${UAM_LOCAL_VERSION_MINIMUM}" reserved)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${reserved}")
endif()
