# Match source content across platforms; checkout line endings do not change the contract.
if(NOT DEFINED UAM_SOURCE_ROOT)
  get_filename_component(UAM_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(UAM_RUNNER_GLOB_DEPENDS "")
if(NOT CMAKE_SCRIPT_MODE_FILE)
  set(UAM_RUNNER_GLOB_DEPENDS CONFIGURE_DEPENDS)
endif()
file(GLOB_RECURSE UAM_RUNNER_CONTRACT_SOURCES ${UAM_RUNNER_GLOB_DEPENDS} LIST_DIRECTORIES false
  "${UAM_SOURCE_ROOT}/src/common/*.h" "${UAM_SOURCE_ROOT}/src/common/*.cpp" "${UAM_SOURCE_ROOT}/src/common/*.mm"
  "${UAM_SOURCE_ROOT}/src/remote/*.h" "${UAM_SOURCE_ROOT}/src/remote/*.cpp")
list(APPEND UAM_RUNNER_CONTRACT_SOURCES "${UAM_SOURCE_ROOT}/CMakeLists.txt")
list(SORT UAM_RUNNER_CONTRACT_SOURCES)
if(NOT CMAKE_SCRIPT_MODE_FILE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${UAM_RUNNER_CONTRACT_SOURCES})
endif()
set(UAM_RUNNER_SOURCE_RECORDS "")
foreach(source IN LISTS UAM_RUNNER_CONTRACT_SOURCES)
  file(RELATIVE_PATH relative "${UAM_SOURCE_ROOT}" "${source}")
  file(READ "${source}" source_content)
  string(REPLACE "\r\n" "\n" source_content "${source_content}")
  string(SHA256 checksum "${source_content}")
  string(APPEND UAM_RUNNER_SOURCE_RECORDS "${relative}:${checksum}\n")
endforeach()
string(SHA256 UAM_RUNNER_SOURCE_FINGERPRINT "${UAM_RUNNER_SOURCE_RECORDS}")
file(READ "${UAM_SOURCE_ROOT}/src/remote/runner_protocol.h" UAM_RUNNER_PROTOCOL_HEADER)
string(REGEX MATCH "kRunnerProtocolVersion = ([0-9]+)" UAM_RUNNER_PROTOCOL_MATCH "${UAM_RUNNER_PROTOCOL_HEADER}")
set(UAM_RUNNER_PROTOCOL_VERSION "${CMAKE_MATCH_1}")
if(NOT UAM_RUNNER_PROTOCOL_VERSION MATCHES "^[0-9]+$")
  message(FATAL_ERROR "The runner protocol version could not be read from its source contract.")
endif()
