if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VERSION OR
   NOT DEFINED VERSION_OUTPUT)
  message(FATAL_ERROR "INPUT, OUTPUT, VERSION, and VERSION_OUTPUT are required")
endif()
file(SHA256 "${INPUT}" hash)
file(WRITE "${OUTPUT}" "${hash}\n")
file(WRITE "${VERSION_OUTPUT}" "${VERSION}\n")
